Make doc building more robust

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,8 +20,8 @@ gcc --version
 
 echo
 echo "Building documentation..."
-./text_to_markup.py -html < USAGE > evolvotron.html
-./text_to_markup.py -qml -s < USAGE > libevolvotron/usage_text.h
+if ! ./text_to_markup.py -html < USAGE > evolvotron.html ; then echo "Couldn't build evolvotron.html" ; fi
+if ! ./text_to_markup.py -qml -s < USAGE > libevolvotron/usage_text.h ; then echo "Couldn't build libevolvotron/usage_text.h" ; fi
 if ! test -s libevolvotron/usage_text.h ; then echo "\"Full online documentation not available due to problem during build configuration\"" > libevolvotron/usage_text.h ; echo "Something went wrong, used documentation fallback plan"; fi
 echo "...built documentation"
 
